@extends('webflow.layouts.app')

@section('title', 'Glossary')

@section('content')
<div class="container py-4">
    <h1 class="mb-2">Glossary</h1>
    <p class="text-secondary mb-4">Webflow slug: <code>glossary</code> | Path: <code>/glossary</code></p>

    <section class="mb-3">{!! '<h1 class="display-10 mid text-light">Glossary</h1>' !!}</section>
    <section class="mb-3">{!! '<p class="paragraph-37">The following is a list of common window terms to help you in your quest of researching windows.</p>' !!}</section>
    <section class="mb-3">{!! '<a href="#styling" class="template-pages---nav-item-link">Window Replacement</a>' !!}</section>
    <section class="mb-3">{!! '<a href="#editing-pages" class="template-pages---nav-item-link">Energy Efficient windows</a>' !!}</section>
    <section class="mb-3">{!! '<a href="#useful-notes" class="template-pages---nav-item-link">Energy Star</a>' !!}</section>
    <section class="mb-3">{!! '<h2 class="mg-bottom-small">Windows Replacement</h2>' !!}</section>
    <section class="mb-3">{!! '<p class="paragraph-35">The thought of replacing all or most of your old windows with new ones can be daunting and understandably so. Replacing windows throughout your house could be expensive, not to mention inconvenient but don\'t get too discouraged right away. With proper planning to ensure you install the right windows, ones that meet your needs, vision, and budget, this could be one of the best and most financially wise decisions of your life.</p>' !!}</section>
    <section class="mb-3">{!! '<h4 class="mg-bottom-extra-small">Understand why window replacement is necessary.</h4>' !!}</section>
    <section class="mb-3">{!! '<p class="paragraph-36">There are many reasons that people choose to replace old windows; Appearance, deterioration, maintenance and energy efficiency are just a few. Once you decide to purchase new windows for your home and the reason you are replacing them, you automatically narrow down your search, making it easier to reach a decision. Some materials may be better for energy efficiency, others because they fit in with the aesthetic of your home.</p>' !!}</section>
    <section class="mb-3">{!! '<h4 class="mg-bottom-extra-small">Set a budget.</h4>' !!}</section>
    <section class="mb-3">{!! '<p class="paragraph-38">Deciding on the number of windows you need to replace and setting a budget that works for you should be your next step. Windows are generally priced very differently; hence, the number of windows you will be replacing will help you determine the most economical style of window.</p>' !!}</section>
    <section class="mb-3">{!! '<h4 class="mg-bottom-extra-small">Choose your style.</h4>' !!}</section>
    <section class="mb-3">{!! '<p class="paragraph-39">The best way to start is to think about the rooms in which the windows will be placed. Do they face the front of the house or are they hidden at the back? It\'s more than acceptable to use several styles throughout your home, keep in mind, however, that some windows need a little more maintenance than others. For example wood windows require a little more up-keep than <a href="https://bayareawindowpros.com/windows/material/vinyl" data-w-id="2d46f973-2e9e-e34c-8e3a-565711a8481c">vinyl</a>, which are virtually maintenance free. However the aesthetic benefits of wood usually far out way the maintenance they need over the years, as always personal preference is key.</p>' !!}</section>
    <section class="mb-3">{!! '<h4 class="mg-bottom-extra-small">How can I get more information?</h4>' !!}</section>
    <section class="mb-3">{!! '<p class="paragraph-40">When you request a <a href="/" data-w-id="1d671975-86b8-15fd-4b71-5d4d45fee992">free quote</a> you will have a chance to learn more about your options and speak with a licensed home improvement professional. We\'ll make sure that you have the information you need to make a well thought out decision that\'s right for you.<br data-w-id="1d671975-86b8-15fd-4b71-5d4d45fee996"></p>' !!}</section>
    <section class="mb-3">{!! '<h2 class="mg-bottom-small">Energy Efficient Windows</h2>' !!}</section>
    <section class="mb-3">{!! '<h4 class="mg-bottom-extra-small">What are Green or Energy Efficient windows?</h4>' !!}</section>
    <section class="mb-3">{!! '<p class="mg-bottom-default">Green or energy efficient, windows are windows that transmit the least amount of heat and reduce your home energy output. They also protect your home temperature from being affected by the external weather.<br data-w-id="9537576e-a49b-f2de-098e-5a52653ff9cc"><br data-w-id="02f59e6c-1b6c-435e-1a63-11e1a7add026">- Most of the heat loss in the home is caused by the windows, because of the type of glass and/or type of frame. This is because older windows, typically aluminum windows, are conductors meaning they transmit heat and cold.<br data-w-id="6c0692a3-ebc2-eab2-5975-4881f91ae3d8">- Installing green windows into your home will not only maintain the desired temperature of your home but in the long run will save you money on heating and cooling bills. Windows that are considered "green" insulate your home and decrease heat transfer making your home more energy efficient.</p>' !!}</section>
    <section class="mb-3">{!! '<h4 class="mg-bottom-extra-small">What determines energy efficiency of a window?</h4>' !!}</section>
    <section class="mb-3">{!! '<p class="mg-bottom-default">The type of glass used for a window, determines its efficiency rate how much and what kind of light will be let in. <br data-w-id="b3bb0146-4726-8553-4c88-3fe41fadcbd1">- The newest technology for glass allows for a large reduction in heat loss. With a particular type of glass called "Low-E," or low emissivity, energy efficiency becomes possible.<br data-w-id="e955d624-53e1-5029-92e5-5728a3d2f892">- Low-E glass allows the visible light to enter the home, but blocks the bad light that damages skin and cause colors to fade. For the highest efficiency, the space between the panes is filled with argon gas to further insulate.<br data-w-id="b693c87f-928d-db37-cdfb-3f560ca8cae9">- Warm edge spacers in between the panes also reduce heat transfer as well as insulate the edges creating a highly efficient "green" window.<br data-w-id="fe392442-ea92-b440-345a-8a32c265e1bb">- For even greater efficiency, the frames of energy efficient windows are made with materials that also help reduce heat transfer while increasing insulation, like vinyl or fiberglass.<br data-w-id="fd17b947-c723-41d2-987f-9a9c0d90760d"><br data-w-id="ffbf9921-3434-cfc2-b90b-71af1bda555b">The circle graph above shows that one-quarter of your carbon footprint consists of home energy use, but this can vary depending on the kinds of energy sources available to power your home. ENERGY STAR calculates carbon savings for ENERGY STAR windows, doors, and skylights based on the mix of fuels in a region and the estimated energy use for a typical home.</p>' !!}</section>
    <section class="mb-3">{!! '<h2 class="mg-bottom-small">Energy Star</h2>' !!}</section>
    <section class="mb-3">{!! '<p class="paragraph-41">ENERGY STAR is the trusted, government-backed symbol for energy efficiency helping us all save money and protect the environment through energy-efficient products and practices.<br data-w-id="f144c34e-8b78-31a9-645f-d95769248bfd">‍<br data-w-id="4b5e866e-938b-a8ad-1ff7-dad89e9afb81">The ENERGY STAR label was established to:Reduce greenhouse gas emissions and other pollutants caused by the inefficient use of energy; andMake it easy for consumers to identify and purchase energy-efficient products that offer savings on energy bills without sacrificing performance, features, and comfort.</p>' !!}</section>
    <section class="mb-3">{!! '<h4 class="mg-bottom-extra-small">How Does EPA Choose which Products Earn the Label?</h4>' !!}</section>
    <section class="mb-3">{!! '<p class="mg-bottom-default">Products can earn the ENERGY STAR label by meeting the energy efficiency requirements set forth in ENERGY STAR product specifications. EPA establishes these specifications based on the following set of key guiding principles:<br data-w-id="87e0e39a-2365-44c7-6669-aaf7847efec6">- Product categories must contribute significant energy savings nationwide.<br data-w-id="98bafe31-9c7f-d07c-a779-89ae57a28c2e">- Qualified products must deliver the features and performance demanded by consumers, in addition to increased energy efficiency.<br data-w-id="e820fa82-1e96-36a6-f74b-58e70c689e6e">- If the qualified product costs more than a conventional, less-efficient counterpart, purchasers will recover their investment in increased energy efficiency through utility bill savings, within a reasonable period of time.<br data-w-id="8c7987cb-f2bd-f92f-d344-722507043bf2">- Energy efficiency can be achieved through broadly available, non-proprietary technologies offered by more than one manufacturer.<br data-w-id="81fb4b15-ffe9-7f08-9780-5de49f2414ba">- Product energy consumption and performance can be measured and verified with testing.<br data-w-id="384ca9eb-506e-3ea6-ff74-063eb82d80de">- Labeling would effectively differentiate products and be visible for purchasers.<br data-w-id="07f14d13-6009-6ea4-c88c-98306b3884c0"><br data-w-id="ba6c573f-901e-1475-4d50-0f5a19600f16">ENERGY STAR is the trusted, government-backed symbol for energy efficiency helping us all save money and protect the environment through energy-efficient products and practices.<br data-w-id="7238518b-38ab-03a1-55cb-ab6d42220697"><br data-w-id="7238518b-38ab-03a1-55cb-ab6d42220698">The ENERGY STAR label was established to:<br data-w-id="1954d81f-0852-ac47-147b-2af4ec4796d0">- Reduce greenhouse gas emissions and other pollutants caused by the inefficient use of energy; <br data-w-id="c4e46e2f-e986-9d0a-c88b-f8549a811972">- Make it easy for consumers to identify and purchase energy-efficient products that offer savings on energy bills without sacrificing performance, features, and comfort.</p>' !!}</section>
    <section class="mb-3">{!! '<h4 class="mg-bottom-extra-small">How Does EPA Choose which Products Earn the Label?</h4>' !!}</section>
    <section class="mb-3">{!! '<p class="paragraph-42">Products can earn the ENERGY STAR label by meeting the energy efficiency requirements set forth in ENERGY STAR product specifications. EPA establishes these specifications based on the following set of key guiding principles:<br data-w-id="94ce4ee3-a804-c280-215f-6540653b0941">- Product categories must contribute significant energy savings nationwide.<br data-w-id="ec947237-727e-cbd5-6d79-531e5f8be1e7">- Qualified products must deliver the features and performance demanded by consumers, in addition to increased energy efficiency.<br data-w-id="099d1b29-645b-3377-919e-820c6226715d">- If the qualified product costs more than a conventional, less-efficient counterpart, purchasers will recover their investment in increased energy efficiency through utility bill savings, within a reasonable period of time.<br data-w-id="a99ad484-0903-0771-3b21-cd22f7d212d0">- Energy efficiency can be achieved through broadly available, non-proprietary technologies offered by more than one manufacturer.<br data-w-id="51656d5c-5a4f-53ca-2ef5-86d005ef4ceb">- Product energy consumption and performance can be measured and verified with testing.Labeling would effectively differentiate products and be visible for purchasers.</p>' !!}</section>

    @if(!empty($items))
    <section class="mt-4">
        <h2 class="h5 mb-3">Collection items</h2>
        <div class="row g-3">
            @foreach($items as $item)
            <div class="col-12 col-md-6 col-lg-4">
                <article class="card h-100">
                    <div class="card-body">
                        <h3 class="h6">{{ data_get($item, 'field_data.name', 'Untitled') }}</h3>
                        <pre class="small mb-0">{{ json_encode($item['field_data'] ?? [], JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) }}</pre>
                    </div>
                </article>
            </div>
            @endforeach
        </div>
    </section>
    @endif
</div>
@endsection
